#!/usr/bin/python
# -*- coding: utf-8 -*-

import os

red = 31
green = 32
blue = 36

def color_out(color,s):
    return "\x1B[1;%dm%s\x1B[0m" % (color,s)

def run_rsync(source,target,option):
    cmd = "rsync -avzP " + option + " --delete --exclude-from=/root/rsync/file --password-file=/root/rsync/rsync.password " + source + " " + target
    print(cmd)
    os.system(cmd)

hk_sites = [
    "apps.pcpp.cn",
    "code.baifuni.com",
    "code.chinaskin.cn",
    "code.drfx.org",
    "code.mxoxo.cn",
    "code.qianyaso.com",
    "code.sansejin.cc",
    "code.sansejin.com.cn",
    "code.xianya.cc",
    "code.xianya.net",
    "gaokao1",
    "include",
    "leina",
    "m.common",
    "m.qianyaso.net",
    "sem-jianfeitea.com1",
    "w2.jianfeitea.com",
    "w2.xianya.cc",
    "w3.xianya.cc",
    "www.baifuni.com",
    "www.baifuni.net",
    "www.baifuni.net.cn",
    "www.ggjtw.com",
    "www.jianfeitea.com",
    "www.jianfeitea.hk",
    "www.qianyaso.net",
    "www.test.com",
    "www.ve.cn",
    "w2.sansejin.hk",
    "www.xianya.cc"]
    
site_hosts = {
  'exchange.fmkeji.com' : ["rsyncd@14.18.206.137::wwwmain",
                           "rsyncd@114.112.48.228::wwwmain",
                           "rsyncd@192.168.9.232::wwwmain",
                           "rsyncd@202.55.8.137::wwwmain"]
  }

pwd = os.getcwd()
pdir = os.path.dirname(pwd)
site = os.path.basename(pwd)
if pdir == "/data/www":
    if site_hosts.has_key(site):
        targets = site_hosts[site]
    else:
        targets = ["rsyncd@114.112.48.228::wwwmain",
                   "rsyncd@14.18.206.137::wwwmain",
                   "rsyncd@192.168.9.232::wwwmain"]
        if site in hk_sites:
            targets.append("rsyncd@202.55.8.137::wwwmain")
elif pdir == "/data/mobile":
    targets = ["rsyncd@114.112.48.229::mobilemain",
               "rsyncd@14.18.206.137::mobilemain",
               "rsyncd@192.168.9.232::mobilemain"]
else:    
    print("this script can only run in '/data/www' or '/data/mobile' 's sub directory")
    exit(1)

print (color_out(green, "it will sync follow files:"))
run_rsync(pwd, targets[0], "--dry-run")

print (color_out(green,"---------------------------------------------> to :"))
for t in targets:
    print("        " + t)
y = raw_input("enter yes to continue publish \n(" + 
      color_out(red, "!!!remember updatesite first!!!") + "): ")
if y <> "yes":
    print("cancel publish")
    exit(1)
    
for t in targets:
    run_rsync(pwd, t, "")


